### ISSUE TITLE
Event Tracking

### ISSUE THREAD

**Issue by velocitatem** [IERoboticsClub/club-website#12]
Three things this should do:
+ [ ] Display an event on the website
+ [ ] Add an event to the database via an internal interface (at first maybe just an API call or just Notion databases) [issue with notion databases is that the whole integration is really slow. a single API call can be 8s!!!]
+ [ ] list all the recent events

```mermaid
graph TD;
  A[Front-end] -->|Fetch| B[Display Event]
  A -->|Add| C[Add Event to Database]
  A -->|List| D[List Recent Events]
  A -->|Search| E[Search for Events]
  
  B --> G[Database]
  C --> G
  D --> G
  E --> G
  
  G[Database] -->|Optimized API| I[Back-end]
  
  B -.->|Embed| J[Notion]
  C -.->|Add Details| J
  I -.->|Sync| J
  
  J[Notion] -->|Notion API| I
```

**Comment by dsanmart** [comment]
@velocitatem @vtwoptwo @i-be-keggles 

What do you think about this architecture? 

For the Github actions job, there are 2 options:
1. Manually triggered action once the event is uploaded and described in Notion.
2. A scheduled cron job (perhaps the same as the ranking leaderboard) that with 1 API call to Notion detects if there are new events created and then does a new API call per new event page.

About the WhatsApp and IE Connects features, don't worry about it. As mentioned in the meeting, we want to automate as much as possible internally at the club so we might assign this task to one of our officers.

![Image](https://github.com/IERoboticsClub/club-website/assets/92187824/703de4bc-2a8f-48c4-899e-fd27f6df2533)

**Comment by velocitatem** [comment]
That sounds perfect, except the trigger of any action from notion is only for the pro version AFAIK. A scheduled task would probably be better in this case, we can keep the trigger for this tentative for now. Once we have the script to handle the data it doesn't really matter where it runs.

+ [ ] Script to fetch events data from notion

**Comment by velocitatem** [comment]
@dsanmart @vtwoptwo @i-be-keggles 

I think we should completely get rid of the notion in the workflow. It is really a pain to work with and _scraping_ it to get data that we then put into the database is really not a good practice especially for longer-term maintenance. I have been playing with Retool and it can really replace Notion very well in terms of management of data. If we want to keep a list of events for example, itd be better to have it all directly stored in Mongo and interface with mongo via Retool. Like this we have less compute running in the whole process. 

Even user management becomes much easier:
![image](https://github.com/IERoboticsClub/club-website/assets/60182044/158be117-6ab7-4218-88f5-f21cb7e3a7a6)

If at any point we don't want to use retool, all the data is safe and sound in Mongo and can be interfaced with another way. Notion can be kept running as a knowledgebase we can somewhat easily display on the website or just reference it.

+ https://retool.com/

Thoughts?
